{
  imports = [
    ./autocmd.nix
    ./cmp.nix
    ./colors.nix
    ./conform.nix
    ./general-keymaps.nix
    ./gitsigns.nix
    ./godot.nix
    ./guess-indent.nix
    ./lsp.nix
    ./lualine.nix
    ./mini.nix
    ./noice.nix
    ./oil.nix
    ./settings.nix
    ./substitute.nix
    ./telescope.nix
    ./treesitter.nix
    ./undotree.nix
    ./whichkey.nix
  ];
}
