{
  imports = [
    ./autoclose.nix
    ./colors.nix
    ./conform.nix
    ./godot.nix
    ./guess-indent.nix
    ./lsp.nix
    ./luasnip.nix
    ./oil.nix
    ./roslyn.nix
    ./smart-splits.nix
    ./telescope.nix
    ./treesitter-context.nix
    ./treesitter.nix
    ./undotree.nix
    ./whichkey.nix
  ];
}
